{
    "final_name": "Helical_Gear_20T_Module2",
    "final_shape": "Helical Gear with Hub",
    "units": "mm",
    "_template_category": "power_transmission",
    "_editable_parameters": {
        "num_teeth": 20,
        "module": 2,
        "pitch_diameter": 40,
        "outer_diameter": 44,
        "root_diameter": 35,
        "face_width": 20,
        "bore_diameter": 12,
        "hub_diameter": 24,
        "hub_length": 12,
        "helix_angle_deg": 20,
        "pressure_angle_deg": 20
    },
    "_engineering_note": "Helical gear with 20-degree helix angle. Tooth profile simplified as trapezoidal radial extrusions (actual involute helicoidal surface requires specialized CAM). Gear blank is suitable for hobbing. Keyway omitted for simplicity.",
    "parts": {
        "part_1": {
            "coordinate_system": {
                "Euler Angles": [0.0, 0.0, 0.0],
                "Translation Vector": [0.0, 0.0, 0.0]
            },
            "sketch": {
                "face_1": {
                    "loop_1": {
                        "circle_1": {
                            "Center": [0.0, 0.0],
                            "Radius": 17.5
                        }
                    }
                }
            },
            "extrusion": {
                "extrude_depth_towards_normal": 20.0,
                "extrude_depth_opposite_normal": 0.0,
                "sketch_scale": 1.0,
                "operation": "NewBodyFeatureOperation"
            },
            "description": {
                "name": "Gear_Root_Cylinder",
                "shape": "Cylindrical Root Body",
                "length": 35.0,
                "width": 35.0,
                "height": 20.0
            }
        },
        "part_2": {
            "coordinate_system": {
                "Euler Angles": [0.0, 0.0, 0.0],
                "Translation Vector": [17.0, 0.0, 0.0]
            },
            "sketch": {
                "face_1": {
                    "loop_1": {
                        "line_1": {
                            "Start Point": [0.0, -2.2],
                            "End Point": [5.0, -1.2]
                        },
                        "line_2": {
                            "Start Point": [5.0, -1.2],
                            "End Point": [5.0, 1.2]
                        },
                        "line_3": {
                            "Start Point": [5.0, 1.2],
                            "End Point": [0.0, 2.2]
                        },
                        "line_4": {
                            "Start Point": [0.0, 2.2],
                            "End Point": [0.0, -2.2]
                        }
                    }
                }
            },
            "extrusion": {
                "extrude_depth_towards_normal": 20.0,
                "extrude_depth_opposite_normal": 0.0,
                "sketch_scale": 1.0,
                "operation": "JoinFeatureOperation"
            },
            "pattern": {
                "type": "polar",
                "count": 20,
                "center": [0.0, 0.0, 0.0],
                "total_angle": 360,
                "axis": [0.0, 0.0, 1.0]
            },
            "description": {
                "name": "Helical_Gear_Teeth",
                "shape": "Trapezoidal Tooth Pattern (Helix Simplified)",
                "length": 44.0,
                "width": 44.0,
                "height": 20.0
            }
        },
        "part_3": {
            "coordinate_system": {
                "Euler Angles": [0.0, 0.0, 0.0],
                "Translation Vector": [0.0, 0.0, 20.0]
            },
            "sketch": {
                "face_1": {
                    "loop_1": {
                        "circle_1": {
                            "Center": [0.0, 0.0],
                            "Radius": 12.0
                        }
                    }
                }
            },
            "extrusion": {
                "extrude_depth_towards_normal": 12.0,
                "extrude_depth_opposite_normal": 0.0,
                "sketch_scale": 1.0,
                "operation": "JoinFeatureOperation"
            },
            "description": {
                "name": "Rear_Hub",
                "shape": "Cylindrical Hub Extension",
                "length": 24.0,
                "width": 24.0,
                "height": 12.0
            }
        },
        "part_4": {
            "coordinate_system": {
                "Euler Angles": [0.0, 0.0, 0.0],
                "Translation Vector": [0.0, 0.0, 0.0]
            },
            "sketch": {
                "face_1": {
                    "loop_1": {
                        "circle_1": {
                            "Center": [0.0, 0.0],
                            "Radius": 6.0
                        }
                    }
                }
            },
            "extrusion": {
                "extrude_depth_towards_normal": 32.0,
                "extrude_depth_opposite_normal": 0.0,
                "sketch_scale": 1.0,
                "operation": "CutFeatureOperation"
            },
            "description": {
                "name": "Center_Bore",
                "shape": "Cylindrical Through Bore",
                "length": 12.0,
                "width": 12.0,
                "height": 32.0
            }
        },
        "part_5": {
            "coordinate_system": {
                "Euler Angles": [0.0, 0.0, 0.0],
                "Translation Vector": [0.0, 0.0, 0.0]
            },
            "post_processing": {
                "chamfer": {
                    "edge_selector": "top_edges",
                    "distance": 1.0
                }
            },
            "description": {
                "name": "Top_Edge_Chamfer",
                "shape": "Edge Chamfer",
                "length": 44.0,
                "width": 44.0,
                "height": 1.0
            }
        }
    }
}
